### ISSUE TITLE
Error When Training

### ISSUE THREAD

**Issue by zeyuanxy** [rbgirshick/fast-rcnn#10]
Hi, when I run the command:

./tools/train_net.py --gpu 0 --solver models/VGG16/solver.prototxt \
    --weights data/imagenet_models/VGG16.v2.caffemodel

the output is:

Traceback (most recent call last):
  File "./tools/test_net.py", line 13, in <module>
    from fast_rcnn.test import test_net
  File "/home/szy/fast-rcnn/tools/../lib/fast_rcnn/__init__.py", line 9, in <module>
    from . import train
  File "/home/szy/fast-rcnn/tools/../lib/fast_rcnn/train.py", line 10, in <module>
    import caffe
  File "/home/szy/fast-rcnn/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/szy/fast-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 14, in <module>
    import caffe.io
  File "/home/szy/fast-rcnn/tools/../caffe-fast-rcnn/python/caffe/io.py", line 3, in <module>
    from scipy.ndimage import zoom
ImportError: cannot import name zoom

Maybe there are some problems about the dependencies?

**Comment by rbgirshick** [comment]
This appears to be an issue with Caffe and your system. You can seek help in the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.

**Comment by zeyuanxy** [comment]
Cool, thanks :)
