### ISSUE TITLE
Error when run demo.py with cpu mode

### ISSUE THREAD

**Issue by cvDreamer** [rbgirshick/fast-rcnn#117]
Succeeded in building fast rcnn, and try to run 
./tools/demo.py --cpu 
and saw the following error:

......
Demo for data/demo/000004.jpg
Traceback (most recent call last):
  File "demo.py", line 150, in <module>
    demo(net, '000004', ('car',))
  File "demo.py", line 89, in demo
    scores, boxes = im_detect(net, im, obj_proposals)
  File "/Users/Sean/Work/src/fast-rcnn/tools/../lib/fast_rcnn/test.py", line 182, in im_detect
    net.blobs['data'].reshape(*(blobs['data'].shape))
  File "/Users/Sean/Work/src/fast-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 27, in _Net_blobs
    return OrderedDict(zip(self._blob_names, self._blobs))
TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<caffe::Blob<float> >

Any help? Thanks!

**Comment by deboc** [comment]
Seems like an issue with boost version :
https://github.com/BVLC/caffe/issues/3494
