### ISSUE TITLE
train.sh

### ISSUE THREAD

**Issue by riadhayachi** [rbgirshick/fast-rcnn#156]
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/riadh/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 157, in train_net
    pretrained_model=pretrained_model)
  File "/home/riadh/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 51, in __init__
    pb2.text_format.Merge(f.read(), self.solver_param)
AttributeError: 'module' object has no attribute 'text_format
i get this error while running train.sh can any one help me

**Comment by cdshdow** [comment]
adding "import google.protobuf.text_format" in the train.py

**Comment by TitusTom** [comment]
sudo pip install protobuf==2.6.0 fixed this for me.
