### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by Mr956** [rbgirshick/fast-rcnn#176]
l am training a Fast R-CNN detector.By using
`./tools/train_net.py --gpu 0 --solver models/VGG16/solver.prototxt \
	--weights data/imagenet_models/VGG16.v2.caffemodel`
It seems to be working,but there is a error happened.

```
Solving...
I0430 11:30:34.755612  3248 python_layer.hpp:63] Traceback (most recent call last):
  File "/home/li/FRCN_ROOT/tools/../lib/roi_data_layer/layer.py", line 108, in forward
    blobs = self._get_next_minibatch()
  File "/home/li/FRCN_ROOT/tools/../lib/roi_data_layer/layer.py", line 48, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "/home/li/FRCN_ROOT/tools/../lib/roi_data_layer/minibatch.py", line 40, in get_minibatch
    num_classes)
  File "/home/li/FRCN_ROOT/tools/../lib/roi_data_layer/minibatch.py", line 84, in _sample_rois
    replace=False)
  File "mtrand.pyx", line 1192, in mtrand.RandomState.choice
TypeError: 'numpy.float64' object cannot be interpreted as an index
Traceback (most recent call last):
  File "./tools/train_net.py", line 92, in <module>
    max_iters=args.max_iters)
  File "/home/li/FRCN_ROOT/tools/../lib/fast_rcnn/train.py", line 123, in train_net
    sw.train_model(max_iters)
  File "/home/li/FRCN_ROOT/tools/../lib/fast_rcnn/train.py", line 91, in train_model
    self.solver.step(1)
  File "/home/li/FRCN_ROOT/tools/../lib/roi_data_layer/layer.py", line 108, in forward
    blobs = self._get_next_minibatch()
  File "/home/li/FRCN_ROOT/tools/../lib/roi_data_layer/layer.py", line 48, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "/home/li/FRCN_ROOT/tools/../lib/roi_data_layer/minibatch.py", line 40, in get_minibatch
    num_classes)
  File "/home/li/FRCN_ROOT/tools/../lib/roi_data_layer/minibatch.py", line 84, in _sample_rois
    replace=False)
  File "mtrand.pyx", line 1192, in mtrand.RandomState.choice
TypeError: 'numpy.float64' object cannot be interpreted as an index
```

I try to change the numpy version from 1.14.3 to 1.11.0,but there is a another error happened.

```
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "./tools/train_net.py", line 13, in <module>
    from fast_rcnn.train import get_training_roidb, train_net
  File "/home/li/FRCN_ROOT/tools/../lib/fast_rcnn/__init__.py", line 9, in <module>
    from . import train
  File "/home/li/FRCN_ROOT/tools/../lib/fast_rcnn/train.py", line 10, in <module>
    import caffe
  File "/home/li/FRCN_ROOT/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/li/FRCN_ROOT/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: numpy.core.multiarray failed to import
```

Does anyone know what might be causing this problem? I need help , please!

**Comment by kevgeo** [comment]
@Mr956  Have you been able to solve the error?

**Comment by Mr956** [comment]
@kevgeo l have solved this problem,this error is arises because numpy.int can no longer be used as an index.One way to solve this problem if you don't want to change the version of numpy is to change file.
In  minibatch.py line 26
change `fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image)` to
`fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image).astype(np.int)`
In ds_utils.py line 12
change`hashes = np.round(boxes * scale).dot(v)` to 
`hashes = np.round(boxes * scale).dot(v).astype(np.int)`
In test.py line 129
change `hashes = np.round(blobs['rois'] * cfg.DEDUP_BOXES).dot(v)` to 
`hashes = np.round(blobs['rois'] * cfg.DEDUP_BOXES).dot(v).astype(np.int)`
In proposal_target_layer.py line 60
change `fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image)` to
`fg_rois_per_image = np.round(cfg.TRAIN.FG_FRACTION * rois_per_image).astype(np.int)`
In proposal_target_layer.py line 123
change `for ind in inds:
        cls = clss[ind]
        start = 4 * cls
        end = start + 4
        bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]
        bbox_inside_weights[ind, start:end] = cfg.TRAIN.BBOX_INSIDE_WEIGHTS
    return bbox_targets, bbox_inside_weights` to
`for ind in inds:
        ind = int(ind)
        cls = clss[ind]
        start = int(4 * cos)
        end = int(start + 4)
        bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]
        bbox_inside_weights[ind, start:end] = cfg.TRAIN.BBOX_INSIDE_WEIGHTS
    return bbox_targets, bbox_inside_weights`
My computer is not by my side,maybe the line number record is a little wrong,please contact me if it still cannot be solved.

**Comment by chensonglu** [comment]
@Mr956 thx, i solved the problem as you suggested, but the file name and the line number is not same with the current version. For example,  ds_utils.py is deleted and proposal_target_layer.py is merged into minibatch.py. Anyway, thx so much.
