### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by javier-castan** [rbgirshick/fast-rcnn#45]
I'm trying to train a custom dataset following the instructions but I'm getting some errors, I guess the problem is with the input images format (mine are 640x480 and 480x640), can anyone please give me any help with this?

The error I'm getting when training is:

Traceback (most recent call last):
  File "./tools/train_net.py", line 80, in <module>
    roidb = get_training_roidb(imdb)
  File "/workspace/fastrcnn/fastrcnn/tools/../lib/fast_rcnn/train.py", line 107, in get_training_roidb
    imdb.append_flipped_images()
  File "/workspace/fastrcnn/fastrcnn/tools/../lib/datasets/imdb.py", line 104, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError

**Comment by anuchandra** [comment]
A few of us have faced this issue. You can find that discussion here.

https://github.com/rbgirshick/fast-rcnn/issues/11

**Comment by Designbook1** [comment]
I've met the problem too, @javier-castan how to solve it? With thanks.
